model_list:
  - model_name: gemini-flash-latest
    litellm_params:
      model: gemini/gemini-flash-latest
      api_key: os.environ/GOOGLE_KEY
  - model_name: gemini-pro-latest
    litellm_params:
      model: gemini/gemini-pro-latest
      api_key: os.environ/GOOGLE_KEY
  - model_name: gemini-flash-lite-latest
    litellm_params:
      model: gemini/gemini-flash-lite-latest
      api_key: os.environ/GOOGLE_KEY
  - model_name: qwen3.6-plus
    litellm_params:
      model: openrouter/qwen/qwen3.6-plus
      api_key: os.environ/OPENROUTER_API_KEY
  - model_name: deepseek-v4-pro
    litellm_params:
      model: openrouter/deepseek/deepseek-v4-pro
      api_key: os.environ/OPENROUTER_API_KEY
  - model_name: kimi-k2.6
    litellm_params:
      model: openrouter/moonshotai/kimi-k2.6
      api_key: os.environ/OPENROUTER_API_KEY
  - model_name: glm-5.1
    litellm_params:
      model: openrouter/z-ai/glm-5.1
      api_key: os.environ/OPENROUTER_API_KEY
  - model_name: gemma-4-31b-it-free
    litellm_params:
      model: openrouter/google/gemma-4-31b-it:free
      api_key: os.environ/OPENROUTER_API_KEY

litellm_settings:
  drop_params: true

general_settings:
  master_key: os.environ/LITELLM_MASTER_KEY
